stages:
  - linting
  - formatting 



image:
  name: external/docker/debian

black:
  stage: formatting
  before_script:
    - apt update -y && apt upgrade -y && apt install python3 python3-pip python3-venv make -y
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install -r requirements.txt
  script:
    - source .venv/bin/activate
    - make check_format
  
flake8:
  stage: linting
  before_script:
    - apt update -y && apt upgrade -y && apt install python3 python3-pip python3-venv make -y
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install -r requirements.txt
  script:
    - source .venv/bin/activate
    - make lint
    - make typecheck

tuttest:
  stage: formatting
  before_script:
    - apt update -y && apt upgrade -y && apt install python3 make -y
    - pip install tuttest@git+https://github.com/antmicro/tuttest --break-system-packages
  script:
    - make tuttest
