stages:
  - lint_and_style
  - tests

black:
  image: "debian:bookworm"
  stage: lint_and_style
  before_script:
    - apt update -y && apt install python3 python3-pip python3-venv make git -y
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install .[dev]
  script:
    - source .venv/bin/activate
    - make check_format

flake8:
  image: "debian:bookworm"
  stage: lint_and_style
  before_script:
    - apt update -y && apt install python3 python3-pip python3-venv make git -y
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install .[dev]
  script:
    - source .venv/bin/activate
    - make lint
    - make typecheck

tuttest:
  image: "debian:bookworm"
  stage: tests
  before_script:
    - apt update -y && apt install python3 python3-venv cpuset make sudo git gcc gzip bzip2 xz-utils -y
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install git+https://github.com/antmicro/tuttest
  script:
    - source .venv/bin/activate
    - make tuttest

unittest:
  image: "debian:bookworm"
  stage: tests
  before_script:
    - apt update -y && apt install python3 python3-venv make sudo -y
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install .[dev]
  script:
    - source .venv/bin/activate
    - make unittest


ordertest:
  image: "debian:bookworm"
  stage: tests
  before_script:
    - apt update -y && apt install python3 python3-venv make sudo -y
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install .[dev]
  script:
    - source .venv/bin/activate
    - make ordertest

