stages:
  - dependecies
  - linting
  - formatting

image:
  name: external/docker/debian

dependencies:
  stage: dependencies
  script:
    - apt update -y && apt upgrade -y && apt install python3 python3-pip python3-venv make -y
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install -r requirements.txt

black:
  stage: formatting
  script:
    - source .venv/bin/activate
    - make check_format
  
flake8:
  stage: linting
  before_script:
  script:
    - source .venv/bin/activate
    - make lint
