stages:
  #- linting
  - formatting 


image:
  name: external/docker/debian
black:
  stage: formatting
  before_script:
    - apt update -y && apt upgrade -y && apt install python3 python3-pip python3-venv make git -y
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install .[dev]
  script:
    - source .venv/bin/activate
    - make check_format

flake8:
  stage: linting
  before_script:
    - apt update -y && apt upgrade -y && apt install python3 python3-pip python3-venv make git -y
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install .[dev]
  script:
    - source .venv/bin/activate
    - make lint
    - make typecheck

tuttest:
  stage: formatting
  before_script:
    - apt update -y && apt upgrade -y && apt install python3 python3-venv make sudo git gcc -y
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install git+https://github.com/antmicro/tuttest
  script:
    - source .venv/bin/activate
    - make tuttest
