---
matrix:
  thread: [2, 4, 8]
  commit: ["04b536d553a21219d1419820e35d8cd703561636", "32d369e077b7330022d8eda68bcbbfcd25b9e56a"]
  input: ["data1", "data2", "data3"]
run:
  before:
    - "cd ~/Documents/sleeper && git checkout $matrix.commit && make build"
  benchmark:
    - "~/Documents/sleeper/sleeper $matrix.thread $matrix.input"
  after:
    - "cd ~/Documents/sleeper && make clean"
output:
  csv:
    filename: "result.csv"
    format: "csv"
  plot:
    filename: "plot.png"
    format: "bar-chart"
    x-axis: input
    facet: commit
    color: thread
    width: 10
    height: 9
    dpi: 100
  table:
    format: "table-md"
    filename: "table.md"
    columns: ["commit","input"]