---
output:
  name: "result.csv"
  format: "csv"
matrix:
  commit: ["e78af0f465f4df31ab90d47a36a81cab7b5e85a2", "6652eb532aa192b588c73835069f043567edc1b5"]
run:
  before:
    - "cd ~/Documents/sleeper && git checkout $matrix.commit && make build"
  benchmark:
    - "~/Documents/sleeper/sleeper"
  after:
    - "cd ~/Documents/sleeper && make clean"