---
matrix:
  thread: [2, 4, 8]
  tag: ["slow", "fast"]
  input: ["data1", "data2", "data3"]
run:
  before:
    - "git clone . ~/Documents/sleeper"
    - "cd ~/Documents/sleeper && git checkout $matrix.tag && make build"
  benchmark:
    - "~/Documents/sleeper/sleeper $matrix.thread $matrix.input"
  after:
    - "cd ~/Documents/sleeper && make clean"
    - "rm -rf ~/Documents/sleeper"
output:
  csv:
    filename: "result.csv"
    format: "csv"
  plot:
    filename: "plot.png"
    format: "bar-chart"
    x-axis: input
    facet: tag
    color: thread
    width: 10
    height: 9
    dpi: 100
  table:
    format: "table-md"
    filename: "table.md"
    columns: ["tag", "input"]
