---
output:
  name: "result.csv"
  format: "csv"
matrix:
  commit: ["1ff8e7aa46b69badd29c563eea5ad38511587945", "6652eb532aa192b588c73835069f043567edc1b5"]
run:
  before:
    - "cd ~/Documents/sleeper && git checkout $matrix.commit && make build"
  benchmark:
    - "~/Documents/sleeper/sleeper"
  after:
    - "cd ~/Documents/sleeper && make clean"