[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "benchmarker"
readme = "README.md"
version = "0.0.1"
description = "A tool used for automatic benchmarking of software."
requires-python = ">=3.11"
[project.scripts]
benchmarker = "benchmarker.main:main"
