TIME_STAMP_COLUMN = "benchmark_date"
BENCHMARK_ID_COLUMN = "benchmark"
HAS_FAILED_COLUMN = "has_failed"
METRIC_COLUMN = "metric"
STAGE_COLUMN = "stage"
RESULT_COLUMN = "result"
OUTLIER_COLUMN = "outlier"
CONSTANT_COLUMNS = [
    BENCHMARK_ID_COLUMN,
    TIME_STAMP_COLUMN,
    HAS_FAILED_COLUMN,
    OUTLIER_COLUMN,
    METRIC_COLUMN,
    STAGE_COLUMN,
    RESULT_COLUMN,
]
DISPLAYABLE_COLUMNS = [
    BENCHMARK_ID_COLUMN,
    TIME_STAMP_COLUMN,
    HAS_FAILED_COLUMN,
    METRIC_COLUMN,
    STAGE_COLUMN,
]
DEFAULT_STAGE_NAME = ""
